### ISSUE TITLE
Add support for MLFlow version 2

### ISSUE THREAD

**Issue by Andrew-Crosby** [autotraderuk/fastapi-mlflow#13]
MLFlow version 2.0.1 was released in November 2022 ([link](https://mlflow.org/news/2022/11/14/2.0.1-release/index.html)), but fastapi-mlflow support is limited to versions >=1.23.0 <2.0.0.

**Comment by bloomonkey** [comment]
Fixed in [0ec94cd](https://github.com/autotraderuk/fastapi-mlflow/commit/0ec94cd9239841a6d3a50d65d52c5fd7597f6b80)
